---
title: "Checks that R install has worked properly"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(testthat)
```

The output of this file (an html document) can be checked against the version in the github repo to make sure everything is as expected.



## Tidyverse and dplyr

```{r}
library(tidyverse)
expect_equal(lme4::sleepstudy %>% summarize(m=mean(Days)) %>% pull(m), 4.5)
```


```{r}
plt2 <- mtcars %>%
  ggplot(aes(mpg, wt)) + geom_point() + 
  ggthemes::theme_tufte()
expect_is(plt2, 'ggplot')
plt2
```




## RStan

```{r}
# should run a model and show a plot
library(rstanarm)
m1 <- stan_lmer(Reaction~Days+(1|Subject), data=lme4::sleepstudy)
plt <- plot(m1)
expect_is(m1, 'stanreg')
expect_is(m1, 'glm')
expect_is(plt, 'ggplot')
plt
```




## Full Package listing

```{r}
library(pander)
ip <- installed.packages(fields = c("Version")) %>%
  as.tibble() %>%
  select(Package, Version)

tab <- ip %>%
	pander::pandoc.table.return()

expect_is(tab, "character")
expect_match(tab, "colorspace") # match some of the output
expect_match(tab, "tidyverse")

ip %>% 
  pander()
```







